# Generated by Django 5.1.5 on 2025-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='audio_link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_duration',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_instance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='transcript',
            field=models.TextField(),
        ),
    ]
